theme = "catppuccin_mocha"

[editor]
true-color = true
end-of-line-diagnostics = "hint"
color-modes = true

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"

[editor.inline-diagnostics]
cursor-line = "warning"
